stages:
- name: Build
  steps:
  - runScriptConfig:
      image: vacazarottoaws/springucs:latest
      shellScript: |-
        mkdir -p /opt/app
        ln -s `pwd` /opt/app/pipeline-java
        cd /opt/app/pipeline-java
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: java-server:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34252
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
