apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
  #namespace: go
  labels:
    app: springucs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springucs
  template:
    metadata:
      labels:
        app: springucs
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: springucs
          image: vacazarottoaws/springucs:latest
          ports:
            - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: java-service
  #namespace: go
spec:
  selector:
    app: springucs
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #namespace: go
  name: java-ingress
  annotations:
    #allow.http: "false"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default

spec:
  rules:
    - host: springucs.rancher.vagnercazarotto.com
      http:
        paths:
          - path: /
            backend:
              serviceName: java-service
              servicePort: 80